### ISSUE TITLE
LibreOffice extension

### ISSUE THREAD

**Issue by marcoagpinto** [TiagoSantos81/PortugueseLibreOfficeExtension#1]
Hello Tiago,

I was wondering if you could commit to Gerrit your version of the pt_PT speller since Minho University simply ignores all the suggestions I sent them for some 10+ years (or close).

Also, I tried to install manually your OXT and now LibreOffice has the Minho speller and yours, and doesn't allow me to uninstall Minho's :-(

Also, is there a postreform and prereform? Also for Firefox?

Thank you!

**Comment by marcoagpinto** [comment]
@TiagoSantos81 

I have been able to delete the folders that had the Minho University spellers, and only have your oxt installed.

But, LO doesn't detect typos in red, it underlines them as unidentified words (LanguageTool).

How can I fix it?

Thank you!

**Comment by marcoagpinto** [comment]
![error_tiago_20190301](https://user-images.githubusercontent.com/5192600/53623097-f0874780-3bf3-11e9-8973-c90aeb870ec1.png)

**Comment by marcoagpinto** [comment]
Tiago,

I have renamed the profile folder and the Minho speller is gone.

I have installed yours, but LO doesn't recognise pt_PT as being installed.

How do I fix it?

Thanks!

**Comment by TiagoSantos81** [comment]
Hi Marco,
I haven't updated and tested this for awhile. It used to work on the Windows normally. Linux version uses the system hunspell location for spell checking. Maybe some changes on how extensions works now. 
Please confirm your test setup (SO version and LO version).
One of these days I will have a look at it.

**Comment by marcoagpinto** [comment]
> Please confirm your test setup (SO version and LO version).

Windows 10 GB x64 and LibreOffice 6.2.1.2 x64.

**Comment by TiagoSantos81** [comment]
Hi Marco,

I had a looked into the file and updated it. There was an empty line I had forgotten in one of the last commits. I have updated just the dictionary. If possible, copy over the dictionary (https://raw.githubusercontent.com/TiagoSantos81/PortugueseLibreOfficeExtension/5f1f858c5a29b46bf905bc0b85e8500a3e1766ee/dictionaries/pt_PT.dic) and check if the error is gone. Ifso,I will update the extensions again.

**Comment by marcoagpinto** [comment]
@TiagoSantos81 

Yes, it worked! Thanks!

But, before you update the extensions, could you add the following missing words which I suggested numerous times to Minho University, and they never implemented them?

Thanks!
====
alvejável
AutoCAD
autoproclamada
baseámo-nos
buldózeres
cache
confiabilidade
Darwinista
difundível
disrupções
dissipativo
espacialmente
Euromilhões
Excel
feromonas
Fisher
flanqueamento
forrageamento
heterogénica
impassáveis
insurgências
interrelacionadas
jackpot
matematizável
multiagente
multidimensionais
mutado
Neumann
pelotões
pixelização
preditor
proibitivos
propomo-nos
rastreamento
screenshot
screenshots
Shannon
subnacionais
supressivos
teoristas

**Comment by TiagoSantos81** [comment]
Your wordlist was added to the extension.
Please install with the extension and report back if you find any issue. Thank you for the feedback so far.

**Comment by TiagoSantos81** [comment]
@marcoagpinto If you wish to suggest more words, we can do the following:

1. If the word pertains all Portuguese variants, you can add it to LanguageTool hunspell/spelling.txt file. I will add it later once we gather enough words.
2. The word only pertains Portugal Portuguese AO90, suggest on issue #2.
3. The word pertains only Portugal Portuguese pre-AO90, suggest on issue # 3

**Comment by marcoagpinto** [comment]
Hello Tiago,

After attempting to install over V3.0 I get again an error window:
![pt_speller_error_20190301](https://user-images.githubusercontent.com/5192600/53653207-ba24e900-3c42-11e9-94c6-a14186d3bc61.png)

Also, in the GitHub repository, could you add the version number to the filename?

Thanks!

**Comment by marcoagpinto** [comment]
ahhhh... right-click and "remove" also gives an error... it doesn't allow me to install or uninstall the dictionary.

**Comment by marcoagpinto** [comment]
It works only with a renamed profile (change the folder name to remove all extensions).

I can confirm that the words I suggested are working, although not all of them appear underlined with the "non-identified" colour, which makes me wonder if the same happened to the blocks of words I have been pasting to add POS information (in this case there are lots of words which required POS information and I wasn't notified by LanguageTool).

**Comment by TiagoSantos81** [comment]
> It works only with a renamed profile (change the folder name to remove all extensions).

This is new to me. I will check that on my Windows copy once I have some time, and try to see what's wrong. Maybe I will also have to check the new extensions as well for comparison.

> I can confirm that the words I suggested are working, although not all of them appear underlined with the "non-identified" colour, which makes me wonder if the same happened to the blocks of words I have been pasting to add POS information (in this case there are lots of words which required POS information and I wasn't notified by LanguageTool).

The LT rule I added only checks POSs and it is unrelated with the hunspell dictionary in use. At least, in the standalone tool, if the word is not recognized by the dictionary it shows a red underline, regardless of having a POS or not.
