### ISSUE TITLE
Todos os erros aparecem como palavras inexistentes

### ISSUE THREAD

**Issue by marcoagpinto** [TiagoSantos81/PortugueseLibreOfficeExtension#4]
Olá Tiago,

Na tua extensão, sempre que há um erro ortográfico, o LanguageTool reporta como “palavra inexistente” e não aparece sublinhado a vermelho.

**Comment by TiagoSantos81** [comment]
Não percebo.
O LanguageTool usa os meus dicionários. Tanto no site como na ferramenta standalone parece estar a funcionar bem. Podes enviar uns screenshots a mostrar o problema para eu perceber?

**Comment by marcoagpinto** [comment]
Aqui está o screenshot:
![sem_erros_ortograficos_20190305](https://user-images.githubusercontent.com/5192600/53805969-8e0baf80-3f43-11e9-9188-9acc292be3cf.png)

**Comment by TiagoSantos81** [comment]
Consegui reproduzir o erro no LO 6.2. Este é um comportamento novo para mim.
No entanto, parece ser um problema típico do Libreoffice. Vê:
https://ask.libreoffice.org/en/question/184513/error-when-installing-extension-connector-couldnt-connect-to-pipe/
Vou comparar com outras extensões, incluindo o teu dicionário de Inglês, e verificar se existe algo diferente que lide com este assunto, mas, como vejo, isto é um bug do LibreOffice. A extensão e todos os seus ficheiros são instalados com sucesso.
Vou adicionar a etiqueta LibreOffice 6.2 a este assunto.

**Comment by TiagoSantos81** [comment]
Se os dicionários da UMinho orem instalados com o pacote base, ficam bloqueados, logo não podem ser reescritos. A solução é não os instalar com o LibreOffice e só instalar a minha extensão, caso se queira utilizá-la. Em alternativa pode-se descompactar a extensão e mover os ficheiros para a pasta das extensões do LibreOffice. Também explicado em #6 .
