### ISSUE TITLE
Regras .AFF pt_PT para o Proofing Tool GUI

### ISSUE THREAD

**Issue by marcoagpinto** [TiagoSantos81/PortugueseLibreOfficeExtension#5]
Olá Tiago,

Estou à espera que saia uma nova versão do PureBasic para atualizar o Proofing Tool GUI:
http://proofingtoolgui.org/

Tens alguma documentação sobre as flags PT?

Queria adicionar à combobox "Aid" que mostra as flags e a explicação.

Obrigado!

**Comment by TiagoSantos81** [comment]
Não fiz documentação. Mas pelos prefixos/sufixos aplicados deve ser fácil prever.
