### ISSUE TITLE
LibreOffice 6.2.4 ainda não reconhece o teu dicionário

### ISSUE THREAD

**Issue by marcoagpinto** [TiagoSantos81/PortugueseLibreOfficeExtension#6]
Tiago,

O teu dicionário continua a não ser reconhecido pelo LibreOffice.

Ele não substitui o da Universidade do Minho no Gestor de Extensões.

Mesmo eliminando o do Minho ao alterar a pasta respetiva, o teu continua a não funcionar e, quando o tento remover, dá sempre erro.

**Comment by TiagoSantos81** [comment]
Desculpa a demora mas só vi isto agora.
As extensões do LibreOffice pré-instaladas são protegidas (o cadeado em cima delas). Se na instalação escolheres instalar os dicionários portugueses não será possível instalar por cima. O mesmo se passa com qualquer outro idioma ou add-on.
Solução: Instalar sem a extensão ou copiar manualmente os ficheiro para a localização correta.
