### ISSUE TITLE
Palavras exclusivas do Português de Portugal, pré e pós Acordo Ortográfico de 90

### ISSUE THREAD

**Issue by marcoagpinto** [TiagoSantos81/PortugueseLibreOfficeExtension#7]
Canelhas (nome de pessoa)
Chasqueira (nome de pessoa)
Ortins (nome de pessoa)
Al-Qaeda
ISIS
bitcoins
Daesh
teorista
tag
tags
indefinitivamente
toolkit
toolkits
crashes
supervisionamento
superinteligência
reset
lossless
cossenos
preview

**Comment by TiagoSantos81** [comment]
Melhor adicionar ao `spelling.txt` to LanguageTool. Quando importo para o LibreGrammar eu faço uma revisão e de tempos a tempos faço o update também aqui.
De notar que os estrangeirismos também se aplicam às outras nacionalidades e que:
`indefinitivamente ` é um possível erro de digitação
cosseno julgo ser só no novo AO
